### ISSUE TITLE
Include the word 'friend zoned' in the list

### ISSUE THREAD

**Issue by karanchahal** [o-d-i-n/EvilWords#3]
As we hate the word and all that it represents.

**Comment by amaneureka** [comment]
We could add a universal dictionary, people are free to port such dictionary and improve it.

+1 cool idea.

**Comment by mbad0la** [comment]
@amaneureka, but won't we need to regulate the dictionary so that it's data remains viable? Also why do we have the current dictionary in .csv format? Any specific reasons for that?

**Comment by mananpal1997** [comment]
is this issue dead? :stuck_out_tongue:

**Comment by mbad0la** [comment]
@karanchahal , what say?

**Comment by karanchahal** [comment]
Yeah
